### ISSUE TITLE
Core meeting I: Agenda [November 2016]

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#105]
Draft Agenda for Core Meeting 1. Copied from https://github.com/clojurebridge-berlin/organization/issues/74
- [x] launch/open the sign-up forms
- [x] organizational stuff
  - keep in touch with volunteers
  - how to hand out tasks
- [x] reach out to new groups
  - facebook groups
  - mailing lists: reflect-info
  - groups like Female Pressure
  - non-internet outreach, e.g. flyers in libraries; posters
  - local radio
  - schools ; universities
- [x] catering
  - one caterer for coaches event + installfest, e.g. sandwiches
  - one caterer for the main event
  - breakfast
  - drinks: wunderlist?
- [x] swag (additional to notebooks? if any?) 
  - get books and get them signed at EuroClojure!
- [x] orga-hoodies
  - do we really want to do it?
  - who is paying?
- [x] sponsors
  - Tiers - review PR 
- [x] hand out initial tasks
- [x] open form

**Comment by plexus** [comment]
## Core Meeting I

### launch/open the sign-up forms
-   photo question: already removed (thx @vsmart)
-   PoC question
  -   controversial, hard to phrase nicely
  -   if we ask it we need to explain why
  -   possible way out
    -   how would you identify? -> also not ideal, overlaps with the gender identity question
    -   do you belong to other groups that are not well represented in tech?
  -   What will we actually do with it? do we change our selection process?
  -   conclusion: let's not ask it, but try to get a more diverse representation through outreach
-   with that decided we are ready to launch the form

TODOS follow up
-   tweet
-   send mailing list post

### coaches form
-   Nothing done yet
-   Can be copied

TODO
-   Set up the form + email notification

### organizational stuff
-   keep in touch with volunteers
  -   we don't really have a volunteer working at the moment
  -   we do have a bunch of people we know we can ask, most are in Slack, there's no formal list for the rest
  -   volunteers are mostly useful at the workshop itself
  -   we'll ask around when we actually have tasks that volunteers could do
-   how to hand out tasks
  -   Careful assigning other, better for people to just assign themselves!
  -   we don't have much of a process, people's availability varies, this
    means it's chaotic sometimes. Suggestions welcome on how to improve this.
    -   Kanban board, leave things in the backlog, let people pick them up
    -   Pair organizing can help here, meet up with your pair, get stuff done!
  
  TODO
  -   "gardening/curating" of the kanban board, make sure the necessary tasks are there

### reach out to new groups

@vsmart will take the lead in this
-   posters worked well, we should do that again
-   this is an area everyone can help with, think which spaces you come where not a lot of tech people hang
-   suggestions, online
  -   facebook groups
  -   mailing lists: reflect-info
  -   groups like Female Pressure
-   suggestions, offline
  -   non-internet outreach, e.g. flyers in libraries; posters
  -   local radio
  -   schools ; universities
  -   Berliner Fenster = TV in the U-Bahn -> if we can get a news article, then we could try to get on there

TODO
-   Finish and print the posters
-   Put them up! Go flyer!

### design / branding

Tibor would like to push our branding a bit more. Is that ok? Can we change
the logo, decide on branding fonts, use those on posters on website, etc.

This should be ok, be respectful of the previous designs. ClojureBridge logo
should not be changed. ClojureBridge Berlin logo can be discussed.

### Drinks

Wunderlist can take care of drinks again. Typical stuff: water, bionade,
cola, fanta, also coffee and tea.

If we want something else we can ask for it. (-> club mate)

### catering
1.  Breakfast
   
   Last time we had
   -   30 chocolate muffins
   -   30 carrot cake muffins
   -   30 vollkornbrötchen
   
   Vollkornbrötchen weren't a huge success, might be better if we also make
   sure we buy several spreads. @vsmart will look at what options there are at
   the bakery.
2.  Coaches + InstallFest
   
   TODO
   -   Ask a quote from [NoTiers](http://notiers.de/) for coaches + installfest
   -   Ask a quote from Miriam Lappenberg/Cafe Federica for the main event
   -   Order branded cupcakes for the afternoon
   
   All day: fruit, trail mix, etc.

### Capacity

Last time we invited 37 attendees, ~35 were there, 20-ish coaches, + orga +
volunteers meant about 70 people

This time we'll aim for 40 attendees, 25 coaches, 15 orga+volunteers

### swag (additional to notebooks? if any?)
1.  Notebooks
   
   Are stashed away at Wunderlist
2.  T-shirts
   
   People are divided on t-shirts, general concencus seems to be that a generic
   ClojureBridge Berlin t-shiry, without dates or sponsors, and that can be
   reused across workshops, would be nice to have.
   
   How big the batches should be, which sizes etc is harder to estimate. This
   is what we had last time, Tibor will check prices and report back.
   
   We no longer want Stella & Stanley, we're fine with ordering from Cotton.de
   again.
   
   (Last time we had:
   -   27 x Stella Wants (navy blue): 9 S, 16 M, 1 L, 1 XXL
   -   32 x Stanley Acts (navy blue): 1 S, 21 M, 7 L, 1 XL, 2 XXL
     )
3.  Stickers
   
   We still have about 1200 ClojureBridge stickers, we'll need a big bunch of
   these for EuroClojure though.
   
   Would be nice to have ClojureBridge Berlin stickers. If we order more we
   can also get new Clojure Berlin stickers.
4.  Books
   
   Last time we raffled out three copies of "Clojure for the Brave and True".
   We can maybe raffle out a bit more this time, like 3x brave clojure, 3x
   living clojure.
   
   Carin Meyer (gigasquid), author of Living Clojure, will be at EuroClojure,
   we can take some books there to get signed.
   
   Lisa is going by car, she can take the books to Bratislava.

### orga-hoodies

We can already order a batch now for the organizers.

People pay for them themselves.

You are all warmly invite to give feedback on the design ==> https://github.com/clojurebridge-berlin/organization/issues/96

We'll let people sign up during the workshop if they also want one, they can pick it up at the study group.

### Sponsors

The [sponsor page](http://clojurebridge-berlin.github.io/sponsor-us/) has been updated, so you can start looking for sponsors now!

Three tiers now, instead of three tiers + small sponsor.

**Comment by plexus** [comment]
### assign tasks

What are people already planning of taking up
1.  Arne
   -   contact sponsors
   -   send mailing list mail
   -   continue doing the finance/Travis stuff
   -   attendee care
2.  Lisa
   -   order books, get them signed, etc
   -   generally available for website stuff
   -   can help with reach-out (mailing lists)
   -   will be kind of swamped the coming weeks, probably more time after, feel free to ping her if you need help
3.  Julia
   -   Arrange the lightning talks
   -   contact potential sponsors
   -   catering, with Julia
4.  Franziska
   -   focus on outreach in the next few weeks
5.  Nicola
   -   will not do merchandising this time :)
   -   will help with outreach
   -   figure out new target groups
   -   sponsors
   -   cupcakes
   -   stuff that nobody picks up
   -   cheat sheets that fit inside the notebooks
6.  Yulia
   -   outreach, getting posters/flyers around the city
   -   help to find coaches
   -   also happy to do stuff with the website
7.  Ben
   -   catering, Julia can help
8.  Saskia
   -   will be gone two weeks before the workshop, better stuff that can be done in the coming weeks
   -   outreach, offline and online, posters around the city
   -   catering
9.  Tibor
   -   design stuff: design + order + production
     -   posters flyers
     -   t-shirts
     -   hoodies
     -   stamps
     -   stickers
     -   cheat sheet
