### ISSUE TITLE
17.10.2016 Core Team Meeting II Agenda [November 2016]

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#113]
- Catch-up from last meeting
- Status update
  - signups so far
  - sponsors
  - outreach
  - swag / merch
  - catering
- Question: Are we offering child care? Who is organizing it? 
- Question: How do we get people to come to the learner's group? 
- Vote to officially adopt the new logo
- EuroClojure booth
- Curriculum

**Comment by Realtin** [comment]
I can try to contact https://goodhands.eu for Child Care things.

**Comment by plexus** [comment]
17 October 2016, 19:00, Babbel

Present: Julia, Franziska, Ben, Kate, Arne
Excused: Jelle, Lisa, Nicola, Tibor, Saskia

# Sponsors
-   Confirmed
  
  <table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">
  <colgroup>
  <col  class="org-left" />
  <col  class="org-right" />
  </colgroup>
  <tbody>
  <tr>
  <td class="org-left">InnoQ</td>
  <td class="org-right">500</td>
  </tr>
  <tr>
  <td class="org-left">Doctronic</td>
  <td class="org-right">600</td>
  </tr>
  <tr>
  <td class="org-left">Bitcrowd</td>
  <td class="org-right">250</td>
  </tr>
  <tr>
  <td class="org-left">PragProg</td>
  <td class="org-right">5 e-books</td>
  </tr>
  <tr>
  <td class="org-left">Adobe</td>
  <td class="org-right">TBD</td>
  </tr>
  </tbody>
  </table>
-   Contacted
  
  <table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">
  <colgroup>
  <col  class="org-left" />
  </colgroup>
  <tbody>
  <tr>
  <td class="org-left">Studio NAND</td>
  </tr>
  <tr>
  <td class="org-left">Blacklane</td>
  </tr>
  <tr>
  <td class="org-left">Soundcloud</td>
  </tr>
  <tr>
  <td class="org-left">Contentful</td>
  </tr>
  <tr>
  <td class="org-left">Ableton</td>
  </tr>
  <tr>
  <td class="org-left">8th light</td>
  </tr>
  <tr>
  <td class="org-left">Babbel</td>
  </tr>
  <tr>
  <td class="org-left">Metosin</td>
  </tr>
  </tbody>
  </table>
-   Declined
  
  <table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">
  <colgroup>
  <col  class="org-left" />
  </colgroup>
  <tbody>
  <tr>
  <td class="org-left">LambdaWerk</td>
  </tr>
  </tbody>
  </table>

# Sign-ups
-   24 attendee sign-ups
-   5 coaches

# Outreach

[Discussed in Issue 100](https://github.com/clojurebridge-berlin/organization/issues/100)
Also [#115 Event Pages/Blogs](https://github.com/clojurebridge-berlin/organization/issues/115) & [Mailing Lists](https://github.com/clojurebridge-berlin/organization/issues/114)

## Mailing lists etc

Contacted several mailing lists. Last time we got a bunch of sign-ups from
the FU LGBTQ mailing list.

We've mostly contacted techy mailing lists so far, would be good to contact
some more non-tech mailing lists.

"Work in Progress", an on-line magazine, might do a feature on us, which
would be 💯. They're also interested in interviewing one of us.

Franka also messaged some feminist blogs, they would put it up.

## Posters/flyers

The order is in, they will arrive at Wunderlist Wednesday. If they get there
in time people can already pick them up at the project group. Franka is
planning to do postering/flyering on Thursday or Friday, you are all welcome
to join! <3

# Swag / Merch

Tibor has been busy making designs for t-shirts and hoodies.

The t-shirt proposal has the logo in the middle, might be better to have it
on the side as pointed out by Malwine on the hoodie issue

[Issue to discuss the t-shirt design](https://github.com/clojurebridge-berlin/organization/issues/117)

[Issue about the hoodies](https://github.com/clojurebridge-berlin/organization/issues/96)

Lisa has ordered the books, she will take them to get signed at EuroClojure. (-> [#110](https://github.com/clojurebridge-berlin/organization/issues/110))

# Catering

[Discussed in Issue 104](https://github.com/clojurebridge-berlin/organization/issues/104)

Not much news yet on this front, but there are several ideas. Julia and Ben
are on it.

It's winter so we might go with Suppenkult again, just try not to order too
much because reheating the soup is a hassle.

# Question: Are we offering child care? Who is organizing it?

Julia knows people at [Goodhands](https://goodhands.eu/), who can arrange this kind of stuff.

Seems we want to do this, so we should announce it ASAP so people know they
can count on it. Franka will add it to the sign-up form, including a
question for the age of the kid.

One person asked if she would be able to breastfeed her baby. We should be
able to offer her a private place. We're not sure if she intends to have the
baby there during the workshop.

# Question: How do we get people to come to the learner's group?

We should bring back the sign-up form, maybe even do a paper form during the
workshop. That brings an extra commitment, and gives us some new input on
what dates/times work, what people are interested in, etc.

This also allows us to gather emails so we can keep people updated about the
project group.

There is some support for setting up a mailing list, mostly as an
announcement list. This would help to keep the people engaged.

The other thing that is needed is a program for the first month or two so
there's a good transition from workshop to project group.

# Vote to officially adopt the new logo

We'll use this logo for all materials, at least for this workshop.

# EuroClojure booth / unsessions

Since we already have the booth, it seems we don't really need a session
about organizing. People can come and chat with us at the booth.

# Curriculum

Would be good if people could already have a look at where we stand. What's
the difference with upstream? What's the situation with NightCode, etc?

# Speakers for lightning talks

Several names/topics come to mind
-   Sara Regan
-   Johannes
-   Project group (Franka, Julia, Ariane, Saskia?)
-   Saskia

There's a [issue to discuss this](https://github.com/clojurebridge-berlin/organization/issues/95)

We might meet more cool people at EuroClojure :D
