### ISSUE TITLE
Orga Meeting - Sept 21 2017

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#177]
Catch up on the last agenda: https://github.com/clojurebridge-berlin/organization/issues/168

## When & Where

* Thursday Sept 21 - 7-9pm
* Where: Travis CI, Rigaer Str 8, 3rd floor (Ring at "Tessa")
* snacks are welcome :sparkles: 

## Agenda for Thursday

* 19:00 arrivals and snack
* 19:15 status checkins:
  * sponsoring #176 
  * speakers #152 
  * catering #149 
  * attendee care
    * travel support?
  * child care #167 
  * curriculum #156 
  * tshirts #163 
  * coaches training #169 
  * workshop day roles -- who wants to MC? volunteer? who's coaching?
  * Discuss email from the 'other' Clojure study group  
  * Spare laptops

* Afterwards: (optional)  shared working time 

After the status updates and checkins, we can spend some time coworking, sitting together and getting a head start on various tasks. 

Did I miss anything? Let me know! 

![gif](https://media.giphy.com/media/TON7phe0r94Dm/giphy.gif)

cc @DanToml @daiyi @pepper-aenn @lislis @socksy @nblumoe @codebeige @daveliepmann @saskali @Realtin @JohannaCarola

**Comment by endocrimes** [comment]
@vsmart I'm unsure if I can make it, but definitely would like to do a status check with the speakers this week, and sort out any next steps for the CircleCI sponsorship

**Comment by vsmart** [comment]
@DanToml sounds good! would be great to get all speakers to fill out the confirmation form so we can get an overview of who's definitely coming!

**Comment by nblumoe** [comment]
I won't be able to make it, we got an event at our daughter's school. BUT please let me know if you need help anywhere.

**Comment by Realtin** [comment]
I won't be there either. I signed up for an event that evening.

**Comment by daiyi** [comment]
unfortunately I scheduled an interview right in the middle ): ): ):

(that's the coolest gif ever though!)

**Comment by saskali** [comment]
I won't be able to join tonight either :( 

My update: I talked to Suppenkult today and chose two vegan soups for the coaches training next week (caribbean pepper and zucchini coconut). They have my contact in case they need to reach me this week or on Thursday. I will send them the delivery and billing address by tomorrow. For the install fest, I will call next week to tell them about food restrictions and choice of soups. 

Also, I got a copy from NextJournal with the information about the Travis transfer. Is there a specific person I should hand this to?

**Comment by plexus** [comment]
@saskali I used to do the communication with Travis regarding the sponsor receipts. If no one is already doing that then I can do that again. Just send the payment details to me (email or slack) and I'll bundle them up and forward them to Travis Foundation (Anika or Laura).

**Comment by plexus** [comment]
@vsmart not sure how many sponsors are going through Travis Foundation this time but maybe mention it at the meeting that people in contact with the sponsors can forward the details to me

- amount
- date of payment
- company name + address
- english or german
- email address of the person that should get the receipt.

**Comment by vsmart** [comment]
@plexus I can mention this. Should only be a few. The full overview ticket is at #176.

**Comment by JohannaCarola** [comment]
Notes Orga Meeting - Sept 21 2017

**Workshop in 2 weeks & 2 days**

_Sponsoring_

see wrap up finances issue #176 
- if you were tagged here, please follow up on these (see “next steps” column)
- if you have any expenses for ClojureBridge / anything you have paid yourself, you can send the receipt to @plexus to get reimbursed by Travis
-  total costs for catering for coaches training / installfest is more than Cognitect agreed to cover. We will only have them cover the installfest catering and use another sponsor for the coaches training. Make sure to get two separate invoices to make this possible!

_Catering_
- breakfast and / or afternoon treats will be covered from Travis budget (i.e. Nextjournal 1000€ sponsoring)
- Schlomos for breakfast #173 : they offer vegan bagels, @pepper-aenn could pick them up in case they don’t offer delivery. Let’s get their "sandwiches", as we have all the moneyz. @pepper-aenn will check with Schlomos about delivery and get an offer for 60 bagels (please use travis foundation as billing address) . FYI: Wooga will provide coffee and tea (they also have soymilk and stuff) 
- lunch catering #149 confirmed: we have a great offer that even includes a salad bar and we’re still under the 1000 EUR budget (yaaaay) → @pepper-aenn will remind them to please label the food 
- coaches training & installfest catering #165 confirmed! (closing the tab which is basically as good as closing the issue, but will not close the issue yet, wait until food has been eaten maybe…)
- afternoon treats #174 : only get donuts this time as there were too much last time. @pepper-aenn will email them to order donuts (75 donuts) will also ask if they offer delivery. Whoever picks them up needs to get a receipt to get reimbursed (or anna will get an invoice, if that’s possible)

_Speakers_ #152 
- only one speaker filled out the speaker’s form so far (Dave’s contact)
- @DanToml offered to check in with speakers, @lislis will also follow-up on potential speakers
Ideas to get more speakers:
- reach out to people that we know?
- someone from the rubygirls?
- would be nice to get someone to do a lightning talk in German (maybe @saskali could do one about Summer of Code?)
- Ellen could maybe do the learner’s group talk? @vsmart will ask her
- Igor would be able to do a lightning talk (German or English) @lislis will ask him
- @lislis get us settled gurl!

_Attendees_
- 34 people confirmed
- no allergies to consider so far (yay)
- 2 people need childcare
- 1 person has an anxiety disorder (reached out to them to ask if there is any thing we should know / could do)
Discussion: travel support
- some people will come to the workshop from outside Berlin (3 coaches & 1 attendee who accepted)
- do we want to cover any travel expenses?
- no we are not covering expenses as it gets kind of complicated and we would have to prioritize one group over another

_Child Care_

→ 2 people need childcare (kids actually have the same age)
→ @vsmart will email the two attendees to let them know we have organized child care (so that they know for sure that this is being organized and to ask them about further details like if the children have allergies!!)

_Curriculum_

@daveliepmann we have a curriculum! all the changes for the base curriculum are in place. No major changes expected. 
Left todo: hard and ugly changes. 
The maria curriculum is complete (7 people will use it), @daveliepmann will still work a bit on it. If anyone wants to take a look at maria is welcome to do so and give feedback.
→ who will coach using maria? 
maria coaches: dave, arne, malwine, jack rusher, matt , saskia, chris
We will pair coaches who want to use maria to work together ( @daveliepmann to coordinate with them) They should, if possible, coach complete newcomers to coding ( @lislis and @JohannaCarola to create groups)

_Coaches_
- we have 31 coaches (kind of too many), @codebeige would not coach if we have too many (he’s really busy anyways), and can do floating coach then and make sure the other floating coaches do their job
- @lislis and @JohannaCarola will assign attendee groups
- @lislis and @JohannaCarola will also do check in with coaches during lunch
coaches training: @socksy and @JohannaCarola will do the training. Main issue during coaches training is explaining to coaches that the way they coach is more important than knowing the curriculum by heart
- try to be more explicit about the fact that coaches should, if possible, only spend the morning on the curriculum and use the afternoon to do quill stuff. Tell them that it’s important that attendees get a chance to do something practical
- to do: send out email to coaches with all infos (venue etc.) - @vsmart will do
- @socksy and @JohannaCarola to make sure to mark in the google spreadsheet who attended the coaches training
- @lislis will now close coaches sign-up
- @daveliepmann to update coaches training slides

_Tshirts_

→ tshirts ordered! Yay! 
This issue #163 is closed
THANKS to @codebeige 🥇 
some small notes: “fitted cut” is now “slim-fit”, colour is also a little different. Zimpler already has the invoice and the Tshirts will be delivered to Wooga (contact person there is informed), we should have more than enough tshirts 👍 

_Workshop Day roles_

Issue #178 
MCs: @lislis & @pepper-aenn 
Door people? vsmart will clarify if we need someone to open / close the door
speaker contact: @lislis & @DanToml 
attendee contact: @JohannaCarola @lislis @pepper-aenn 
childcare contact: @vsmart 
catering:  @pepper-aenn 
emergency phone person: @vsmart 
extra volunteers (signing in people, etc.): @JohannaCarola

_Spare laptops_
- even though none of the attendees said they need a laptop from us, we should be prepared in case there are issues
- send an email to all orga to ask if anyone could bring a spare laptop

_Afterparty_
- at Volksbar again @lislis will reserve a table

_Welcome talk_
- @lislis & @pepper-aenn to update slides

_Other Points_
- @lislis will bring spare posters so we can use them to write info on (recycle, yay!)
- new issue #180 go through day checklist
email from the ‘other’ clojure group
- discussion moved to slack (email posted there)
