### ISSUE TITLE
Should we do demos? 

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#181]
Do we like having demo session at the end of the day? I'm curious how it would work esp given some groups are doing different curriculum. 

Discuss! 

Would love to hear esp from former attendees @JohannaCarola and @pepper-aenn.

**Comment by JohannaCarola** [comment]
YES! 
Even though demos are potentially part of the reason why some attendees in the end feel like they missed out on something (i.e. because other groups made some cool things and they did not), it's still COOL THINGS! 
So, while our (mine and @pepper-aenn 's ) group didn't get to do any creative stuff in the last workshop, it was cool to see what other people did and it motivated both of us (I think, please object if not @pepper-aenn ) to try some clojure at home and to come to the learner's group.

**Comment by JohannaCarola** [comment]
about the different curriculum: I think that if we make sure that all attendees install nightcode on Friday evening (just so they have it) and also give all of them access to the maria curriculum, at the end of the workshop (this should be easier than installing nightcode, @daveliepmann right?) then it should not be too much of an issue that we have two different curricula.

**Comment by pepper-aenn** [comment]
i agree with @JohannaCarola on this. The demos were an additional motivation and creative input to try out more and even join the learners group. It also showed the variety of things you could do with clojure. I think it's a really nice way to close the workshop and keep people interested. :)

**Comment by vsmart** [comment]
Cool, thanks for pitching in @JohannaCarola and @pepper-aenn . It sounds like we're doing demos again! Looking forward to it!
