### ISSUE TITLE
Make coaches' training reminder more direct

### ISSUE THREAD

**Issue by daveliepmann** [clojurebridge-berlin/organization#183]
The reminder email for the coaches' training is indirect and therefore unnecessarily ambiguous about the mandatory nature of the training. We *suggest* they go, using bold:

>**The coaches training is heavily recommended, especially if you've never coached before. If you can't make it to the coaches training night, please send us an email.**

...but recommendations, no matter how heavy, are not the same as mandatory. However we suggest later that it is in fact not just recommended but a requirement to coach:

>If you've attended the coaches training before it's no longer mandatory, but we do highly recommend it.

If it's mandatory (with exceptions), shouldn't we come out and say so in bold? If it's not, shouldn't we remove the word "mandatory"?

**Comment by vsmart** [comment]
👍 +1 "required for first-time coaches".

@daveliepmann feel free to update the wiki page: https://github.com/clojurebridge-berlin/organization/wiki/%5Bemail%5D-Coaches-Training-Reminder

**Comment by daiyi** [comment]
I have made some edits and trimmed down the email!

**Comment by mhuebert** [comment]
The new format looks great.

I wanted to attend the training (sorry I missed it!) but I only quickly skimmed the email to find the date/time, and then put the wrong date in my calendar, as the first and most obvious date mentioned was that of ClojureBridge itself, rather than of the training night which was the subject of the email. It's my fault for not reading carefully, but the new version will make this mistake not possible, thanks @daiyi :).

**Comment by vsmart** [comment]
Thanks @daiyi! I think we can close this.
