### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by jellea** [clojurebridge-berlin/organization#27]
So I've asked my stickerconsultant friend and he said to look no further than http://www.flyeralarm.com/de/content/index/open/id/2736/aufkleber.html. 500x colour outdoor round 5cm cost about 40 euro brutto incl shipping. Since we budgeted 100 euro I think we can do two designs. How about going for one Clojurebridge logo and one more general Clojure (be proud on your new language!) or Clojure Berlin (welcome in your new community!)?

**Comment by martinklepsch** [comment]
They don't do die cut do they? Couldn't find anything on their website. (just wondering)

**Comment by jellea** [comment]
Doesn't seem like they do custom shapes and looking at the prices for the existing shapes it would've have been out of budget anyway. Would've been fun though!

**Comment by plexus** [comment]
FWIW the Chestnut stickers came from Stickma.de on a recommendation from the Hoodie HQ folks. I paid € 87,73 for 500 transparent stickers + shipping. They do die cut "ab € 30 netto" but that's probably very optimistic. Die cuts tend to be significantly more expensive, and since our logo is round we might as well go with round stickers.

**Comment by martinklepsch** [comment]
I was thinking if we get die-cut at a not too high premium we can put "Berlin" close below the logo. I'm fine with regular round stickers as well though. :)

**Comment by Malwine** [comment]
@jellea ordered them
