### ISSUE TITLE
Signup form

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#48]
I copied the old form and tried to incorporate all the ideas we had to make it better. Feedback or improvements much appreciated!

It's in the ClojureBridge.Berlin google drive

https://docs.google.com/forms/d/1yoZVmo4Z8umpO9hmYB32WBv2Tpmjsgxv3zR5rFspvYA/edit#

live form is here:

https://docs.google.com/forms/d/1yoZVmo4Z8umpO9hmYB32WBv2Tpmjsgxv3zR5rFspvYA/viewform

Not everything is translated yet, so I definitely could use some help there. Otherwise we're gonna have some real funny German in there youknowwhatImean :)

**Comment by thatbettina** [comment]
I would like to edit directly in the form, but it's not shared with me. 

Here's my feedback:
- Expand target group from 'women' to 'people identifying as women'
- Add location of workshop
- Remove info re male +1, guest, guest name
- Remove the free text field regarding gender since we specify that it's for people who identify as women?
- Just for us it might be interesting to ask how she found out about us: radio, Twitter, friend, etc.

**Comment by Malwine** [comment]
Translation Suggestions:
- "eine kostenlose Einführung in programmieren für" => "ein kostenloser Einführungsworkshop in die Programmierung für"
- "Männer sind willkommen, wenn sie als Begleitung einer Teilnehmerin kommen." Depends if we keep the plus 1.
- "Mit welchem Gender identifizierst du dich?" I would say: "Mit welchem Geschlecht identifizierst du dich?". Because atm Gender is still an academic term that not everybody is familiar with. And we have the meaning of it in the "identifizierst du dich".
- "English OR German is fine" => "English OR German is ok"
- "Maybe you know about Clojure haven't actually used it." I think there is a BUT missing.
- Experience - needs German translation
- I have read the Code of Conduct, and agree to honor it.  - needs German translation
- All the rest needs to be translated but I guess you know ^^

**Comment by plexus** [comment]
> All the rest needs to be translated but I guess you know ^^

Yes, I do :) I would really like some help from a local with that. I can improvise but you'll have to correct it afterwards anyway. Maybe @lislis or @nicsnet can help? To edit the form I can either invite you to edit the doc, or you can log in to the clojurebridge.berlin account. I can text/signal you the password.

**Comment by plexus** [comment]
These are the translations I need help with

---

Which of these describes you best?

Beginner
You are totally new to programming.

Intermediate, no Clojure
You understand programming concepts like functions, loops, classes. You haven't used Clojure before.

Advanced, no Clojure
You have done a fair amount of programming, just not yet in Clojure.

Intermediate in Clojure
You've played around before with Clojure, maybe you've done a workshop or made something with Quil. You understand the main concepts but need more practice.

Advanced in Clojure
You are quite comfortable programming in Clojure, and would maybe even be able to be assist others.

---

I have read the Code of Conduct, and agree to honor it.

---

We will make photos during the event, these will be used to promote ClojureBridge on social media, and to represent our organization, for example in conference presentations.

A selection of all photos will be made public as "Creative Commons, Non Commercial, ShareAlike, Attribution", meaning they can be used by anyone for any purpose, as long as it isn't commercial use, as long as the source is mentioned, and as long as any derivative work is made available under these same terms.

License summary: https://creativecommons.org/licenses/by-nc-sa/4.0/

If you prefer not to be in these photographs, then we will make sure our photographers honor that.

**Comment by lislis** [comment]
@plexus here you go:

---

Welche dieser Beschreibungen trifft am ehesten auf dich zu?

Anfängerin
Programmieren ist komplett neu für dich.

Fortgeschritte Anfängerin, kein Clojure
Du verstehst Programmierkonzepte wie Funktionen, Schleifen und Klassen. Du hast Clojure vorher noch nicht benutzt.

Fortgeschritten, kein Clojure
Du hast schon einiges programmiert aber eben noch nicht in Clojure.

Fortgeschrittene Anfängerin in Clojure
Du hast schon voher mit Clojure herumgespielt, vielleicht an einem Workshop teilgenommen oder etwas mit Quill gemacht.
Du verstehst die Hauptkonzepte aber brauchst mehr Übung.

Fortgeschritten in Clojure
Du fühlst dich wohl in Clojure zu programmieren und könntest vielleicht andere unterstützen.

---

Ich habe den Code of Conduct (die Verhaltensregeln) gelesen und stimme zu diesen (diese) zu respektieren.

---

Wir werden während der Veranstaltung Fotos machen. Diese werden benutzt um CojureBridge in den sozialen Medien zu bewerben und unsere Organisation, zum Beispiel in Konferenzvorträgen, zu repräsentieren

Eine Auswahl aller Fotos wird unter der Lizenz "Creative Commons, Non Commercial, ShareAlike, Attribution" veröffentlicht. Das bedeutet egal wer kann sie für egal welchen Zweck verwenden solange der Zweck nicht kommerziell ist, die Quelle genannt und solange veränderte Versionen unter genau denselben Bedingungen veröffentlicht werden.

Zusammenfassung der Lizenz: https://creativecommons.org/licenses/by-nc-sa/4.0/

Falls du es vorziehst nicht auf diesen Fotos zu sein dann werden wir sicher stellen dass unsere Fotografen das respektieren.

**Comment by plexus** [comment]
Thank you so much @lislis :heart_eyes: !

**Comment by plexus** [comment]
Alright folks, I think this is ready. Shall we start sharing it?

**Comment by thatbettina** [comment]
YES!

*edited to remove personal data

**Comment by Malwine** [comment]
@plexus and all.
Last year I was more for the Berlin Code of Conduct.
I think it is better than the Bridge Foundry one.

**Comment by Malwine** [comment]
I put some commas in the form. :smile_cat:

**Comment by Malwine** [comment]
Another point for the Berlin Code of Coduct is that it is translated to various languages. Including DE and ENG. http://berlincodeofconduct.org/

**Comment by plexus** [comment]
Ok, that's a very good point. We can swap it out.

**Comment by thatbettina** [comment]
Closing this issue since even the forms are now closed.
