### ISSUE TITLE
Shirt/sticker design

### ISSUE THREAD

**Issue by jellea** [clojurebridge-berlin/organization#50]
Drop your ideas/inspirational stuff here :)

**Comment by nicsnet** [comment]
Sponsor logos on t-shirt? Yes or no? See discussion on https://github.com/clojurebridge-berlin/organization/issues/44 for finding sponsors.

**Comment by nicsnet** [comment]
I meant sponsor name, not logo. This was a miscommunication on my part, sorry!

**Comment by thatbettina** [comment]
Just for the sake of documentation: discharge print please :)

**Comment by plexus** [comment]
Was Martin the only one last time who disliked the TV-tower idea? :P

**Comment by plexus** [comment]
I've been thinking about the t-shirts, and if it actually wouldn't be super convenient to just make generic "clojurebridge berlin" t-shirts, that aren't tied to one specific workshop.

We can't do that now anymore since sponsors already expect to be on them. It's also not as nice as having a unique "I was there" t-shirt, but think of the benefits
- no need to wait until we know all sponsors
- we can order with a safety margin, whatever is left goes to the next workshop
- no stressing about exact amounts and sizing
- no stressing about the deadline, we can easily order one or two months in advance

We can also combine the two, try to order the exact amount for attendees and coaches, but if last minute a few extra people show up, we can still give them a "generic" t-shirt.

**Comment by jellea** [comment]
Just an idea: How about doing beautiful canvas backpacks this time instead of tshirts? No sizing issues, probably cheaper (less sponsors needed), maybe quicker? :)

**Comment by plexus** [comment]
I like it! could you find an image of the kind of thing you're thinking of?

**Comment by jellea** [comment]
@plexus  Was thinking of something not tote-y: http://www.cotton.de/textilien/bags-taschen/cotton-gymsac/ 

others here: http://www.cotton.de/textilien/bags-taschen/

**Comment by martinklepsch** [comment]
:+1: like the idea. As for quicker I think they'll probably need similar time to print stuff. A thing to keep in mind with the backbacks: the surface is folded/non plain more often than not making it harder to identify read stuff printed on the surface. 

Also when ordering (I can do that if wanted) we need to be extra explicit about discharge-printing. Last time I asked for it and they confirmed and then went ahead with another method without asking first (they had valid reasons, but still).

**Comment by martinklepsch** [comment]
PS: last time they needed 10-15 days from order to printing. The email mentions that this are their usual times "during summer" so this might vary in January.

**Comment by thatbettina** [comment]
I hate to be a party pooper, but since we only have 200 euros of a cash sponsor right now, I'd hold off on ordering anything until we get the money. 

@jellea I like the no sizes aspect of the bags, but I'm with @martinklepsch that I never rotate my tote bags because they don't get dirty like t-shirts...so if we want to make our attendees walking billboards, I'm with the t-shirts.

**Comment by Malwine** [comment]
@jellea I LOVE the gymsac-backpack thing with beautiful design! :heart: :heart_eyes:  :heart_eyes_cat: :boom: 
[This](http://www.cotton.de/textilien/bags-taschen/cotton-gymsac/) one you mentioned. Other bags I have like 100.

---

If for some reason we decide for shirts I want to suggest that we order these: http://www.cotton.de/hersteller/continental-clothing/ 
Because Stella&Stanleys naming is not bearable. The naming is based on gender stereotypes. We only chose them the last time for the quality. 
But `continental-clothing` seems to provide the same quality.
(I just that info now.)

**Comment by plexus** [comment]
We have 12 working days left, I guess it's no longer realistic to order t-shirts. It's a bit of a bummer towards the sponsors that expected to be on them. Then again, we didn't get an explicit t-shirt sponsor, so it's easy to justify that way as well.

T-shirts would also have been tricky because looking at the massive amounts of sign-ups, we'll have to carefully balance coach and space capacity to decide how many people we let in.

This is one thing we need to think about better for next time. To order t-shirts three weeks in advance, we need to know exactly who's coming three weeks in advance, which is pretty much impossible.

To good news is: without t-shirts we're well within the sponsor budget, and we will probably build up a bit more of a buffer in Travis foundation for next time.

Is there anything else we can do to give some kind of souvenir (something that's actually useful and won't just create more waste)? I had another look at the gym-bag, it would be cheaper than the t-shirts, and we can just order 100 of the same, but can we still design and get it printed before the workshop?

**Comment by vsmart** [comment]
The gym bags would still be nice. 

Another idea - I love note books as swag, and I think they would be useful for people to take notes during the workshop too. I tried looking into personalised note books but it seems expensive & difficult. We could buy standard ones, and diy personalise them with ClojureBridge and ClojureBerlin stickers?

**Comment by jellea** [comment]
Great idea Franziska! Notebooks should be feasible on short term. Whats the budget? Should have enough stickers left of last year. Will check when home. Maybe we can print a new batch with some programming quotes for on the notebook?

**Comment by plexus** [comment]
I also think the notebooks are a great idea! I can't say exactly yet how much budget there is, but in general it's healthy. I'm still waiting to hear how much LambdaWerk will put in, and if we can work something out with Soundcloud. But t-shirts were by far our biggest cost, and we also have some buffer from last time, so I'm not too worried.

Maybe we can also put the sponsors on there, e.g. on the back or on the inside of the cover. We could just print the logos black and white on sticker paper. Nice and DIY :)

**Comment by thatbettina** [comment]
Yes for the notebooks! Something handwritten instead of all-digital all the time.

**Comment by Malwine** [comment]
Any news here?

**Comment by vsmart** [comment]
@Malwine the notebooks discussion moved to https://github.com/clojurebridge-berlin/organization/issues/46.
