### ISSUE TITLE
Post-workshop attendee email

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#62]
We should send an email shortly after the workshop, with pointers on how to continue. Gathering input here on what to include
- [x] link with discount code for free access to LambdaCasts
- [x] link to apply for ClojureD diversity tickets http://www.clojured.de/
- [x] link to curriculum, so they can review things at home
- [x] link to Land of Quil (?)
- [x] invites for the private group on Clojureverse, and for the Clojure Dojo slack

Actually looking at that list, maybe we should split that in several emails, e.g. one on the day of the workshop, one a week later, etc. It's simply too many "call to actions" to cram into a single email, people will ignore half of it.

And then there is the question of study groups, which is always a bit tricky. I'm going to open a separate issue for that in a bit to recount some of my experiences, because I have a lot of thoughts and feels about that :)

**Comment by Malwine** [comment]
Also some **feedback** would be nice.
Last time just a few people filled it but it was enough to put some of it as impressions on our website.

**Comment by lislis** [comment]
Is it okay if I just copy the old feedback form and include a link to that?

**Comment by lislis** [comment]
this one basically https://docs.google.com/forms/d/1NXmmLb1uq2AOKz36gAqcz_uSM_AMu1IlnGHj4WakwGI/edit?usp=forms_home

**Comment by lislis** [comment]
Draft:

---

Hello once again,

now that you had some time to let the ClojureBridge workshop sink in we want you share some resources for further studies with you.  
The curriculum that you used during the workshop is available here https://clojurebridge-berlin.github.io/curriculum/ So you can go through it at your own pace one more time.
If you enjoyed the creative part maybe The Land of Quil is something for you. It's an app that runs Clojure in your brower and lets you fiddle with Quil examples: http://landofquil.we-do-fp.berlin/

If you just want to stay in the loop, then joining the either the Clojureverse mailing list http://clojureverse.org or the ClojureDojo Slack chat https://clojuredojo.slack.com is the thing for you.

To receive announcements for future workshops (that you can also share with friends) we created a newsletter where you can sign up `newsletter link`.

Overall we would really appreciate it if you could a few minutes and give us some feedback on the workshop. We prepared a form for that: `link to the form`.

Thank you again for participating. We hope you had fun and learnt a lot.

---

**Comment by plexus** [comment]
That clojureverse url in there is the Chestnut mailing list, that's not the one for ClojureBridge. There's a separate group but it's private so I need to invite people to it. Last time I invited everyone but it didn't get much use. I can do the same again, or we can add a public "ClojureBridge Berlin" group to Clojureverse and point people there.

**Comment by lislis** [comment]
@plexus a public one would be the easiest I think. So people can sign up if they really want to. And if they do it themselves they're more likely to use it too.

**Comment by lislis** [comment]
@plexus what do you think about the feedback form? And do you have the link for the mailchimp newsletter?

**Comment by plexus** [comment]
I set up a new public group on Clojureverse

http://clojureverse.org/c/clojurebridge-berlin

For the announcement list people can sign up on our website (clojurebridge-berlin.github.io) or directly here

http://github.us12.list-manage.com/subscribe?u=d788f0653a3e56a367e673beb&id=253a66d08d

I don't have strong opinions on the feedback form.

Yay for in-flight wifi.

**Comment by lislis** [comment]
yay, I'll translate and send the email (hopefully) today

**Comment by jellea** [comment]
One sec need to add some things!

**Comment by jellea** [comment]
The learners group slack doesnt have a public subscribe/invite system setup, so pointing to it might be a bit useless. Also we're pointing to two mailing lists which might be confusing. 
- Added the Clojure meetup next Wednesday. 
- Added clj/quil cheatsheets. 
- Added titles for readability.

---

Hello once again,

Now that you had some time to let the ClojureBridge workshop sink in we want you share some resources for further studies with you.  

### Continue learning

The curriculum that you used during the workshop is available here https://clojurebridge-berlin.github.io/curriculum/ So you can go through it at your own pace one more time. 
If you enjoyed the creative part maybe The Land of Quil is something for you. It's an app that runs Clojure in your brower and lets you fiddle with Quil examples: http://landofquil.we-do-fp.berlin/  
You can find the [Quil cheatsheet here](https://github.com/clojurebridge-berlin/curriculum/blob/gh-pages/outline/cheatsheet-quil.md) and the [Clojure cheatsheet here](https://github.com/clojurebridge-berlin/curriculum/blob/gh-pages/outline/cheatsheet.md).

### Mailing lists

This will be the last email you receive of this workshop. To receive announcements for future Clojurebridge Berlin workshops (that you can also share with friends) we created a newsletter where you can [sign up](http://github.us12.list-manage.com/subscribe?u=d788f0653a3e56a367e673beb&id=253a66d08d).

If you just want to stay updated on whats happening in the Clojure community of Berlin then join the Clojureverse mailing list http://clojureverse.org.

### Clojure Meetup next Wednesday

Wednesday the 10th its time for the monthly Clojure Dojo meetup again. We highly recommend going there because its the best place to ask questions and meet the friendly Clojure community of Berlin and re-meet some coaches or fellow students from the workshop. 
We heard the plan is to solve some "katas", so if you're curious what that means you should [RSVP](http://www.meetup.com/Clojure-Berlin/events/220479398/)! 
The location is still t.b.a. so check in to that link again before Wednesday. 

### Feedback, please!

Please tell use what you've experienced at the workshop! We would like your feedback to improve future workshops. It shouldn't take more than 5 minutes of your time and its of great help for us: `link to the form`. You can also always reach us at clojurebridge.berlin@gmail.com.

Thank you again for participating. We hope you had fun, learnt a lot and hope to see you around at one of our meetups, workshops .

---

**Comment by plexus** [comment]
Instead of "the clojureverse mailing list" can we make it "the ClojureBridge discussion group on Clojureverse" with the link I sent earlier? Sorry I can't do it myself, I can't easily get on a computer right now.

**Comment by vsmart** [comment]
Translated Jelle's version. 

---

Hallo, 

Jetzt da ihr ein wenig Zeit hattet, den ClojureBridge-Workshop zu verdauen, würden wir gern ein paar weitere Resourcen mit euch teilen. 

### ...Und jetzt? Weiterlernen!

Das Curriculum, welches ihr im Workshop benutzt habt, findet ihr [hier](https://clojurebridge-berlin.github.io/curriculum/). So könnt ihr in Ruhe noch einmal in eurem eigenen Tempo durchgehen. 

Wenn euch der kreative Teil des Nachmittags gefallen hat, ist vielleicht The Land of Quil etwas für euch. Land of Quil ist eine App, mit der ihr in eurem Browser mit Clojure und Quil spielen und ausprobieren könnt. http://landofquil.we-do-fp.berlin/  
Ausserdem findet ihr hier das [Quil cheatsheet](https://github.com/clojurebridge-berlin/curriculum/blob/gh-pages/outline/cheatsheet-quil.md) und das [Clojure cheatsheet](https://github.com/clojurebridge-berlin/curriculum/blob/gh-pages/outline/cheatsheet.md).

### Email-Listen

Dies hier ist die letzte Email, die als Teil des Workshops erhaltet. Um weitere Ankündigungen für ClojureBridge Berlin zu erhalten - auch für eure Freundinnen und andere Interessierte - haben wir diesen Newsletter für euch hier: [anmelden](http://github.us12.list-manage.com/subscribe?u=d788f0653a3e56a367e673beb&id=253a66d08d).

Wenn ihr auf dem Laufenden mit der grösseren Clojure-Community bleiben wollt ist vielleicht ClojureVerse was für euch: http://clojureverse.org.

### Clojure Meetup am Mittwoch

Nächsten Mittwoch, der 10. Februar, findet die monatliche Clojure- UserGroup statt. Dies ist eine gute Gelegenheit, die freundliche Clojure-Community in Berlin kennen zu lernen, Fragen zu stellen, und auch bekannte Gesichter vom ClojureBridge Workshop wieder zu sehen.
Bei diesen Meetups gibt es manchmal Vorträge - für dieses Mal haben wir ein paar "Katas" geplant. Mehr Informationen dazu  [hier](http://www.meetup.com/Clojure-Berlin/events/220479398/)! 
Die Location steht noch nicht fest, schaut dafür vor Mittwoch noch mal in den obigen Link hinein. 

### Gebt uns Feedback!

Ganz, ganz wichtig für uns ist von euch zu hören, was wir bei dem Workshop gut oder verbesserungswürdig gemacht haben. Eure Meinung dazu ist sehr wichtig und hilft uns, den nächsten Workshop noch besser zu gestalten. Es sollte nicht mehr als 5 Minuten dauern, `dieses Formular` auszufüllen. Ihr erreicht uns auch auf clojurebridge.berlin@gmail.com.

Vielen, vielen Dank noch einmal für eure Teilnahme! Bis dahin und hoffentlich sehen wir uns bei einem zukünftigen Meetup, Workshop oder der Projektgruppe.

---

**Comment by lislis** [comment]
@jellea @vsmart thank you!!! Sending them now!

**Comment by plexus** [comment]
Ugh I just received the discount codes for clojure/west. Attendees get free tickets, volunteers and coaches get $50 off. It doesn't say which one organizers should use, I guess the volunteer one. 

Shall we send these in one last separate email? We can also include attendees from the previous workshop then.

**Comment by jellea** [comment]
Just put it on Clojureverse?

**Comment by plexus** [comment]
I can't share the discount codes publicly, and none of the new attendees are in the private group. I can post it to the private group and invite people to that topic.
