### ISSUE TITLE
Retro: What was good / better than last time? What to do differently?

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/organization#64]
Dear people,
as I wasn't attending the workshop but I am interested in your spontaneous thoughts about:
**What was good / better than last time? What to do differently?**

Maybe you can post some thoughts about:
- Food
- Organization
- Merchandise
- Curriculum

... etc

**Comment by plexus** [comment]
Hi Malwine,

We have brunch scheduled on Sunday to go over these things. I'll make sure to take notes.

**Comment by jellea** [comment]
Brunch?

**Comment by plexus** [comment]
Sunday 1pm at my place. Am I the only one who has that in their calendar? :)

**Comment by lislis** [comment]
looks like it :D

**Comment by plexus** [comment]
@thatbettina you know about this, right? I swear I didn't make this up by myself :)

**Comment by martinklepsch** [comment]
I know about it too, I think you mentioned it while we were at Kaschk. :)

**Comment by vsmart** [comment]
I can't do Sunday but I think it was the last possible day that @plexus could do before leaving iirc, so feel free to go ahead on Sunday. Otherwise Mon or Tue night would work for me, but like I said, it's ok either way :)

**Comment by Malwine** [comment]
Ok, that's exactly why I opened the issue. It's awesome that we meet but whoever can't come on Sunday can share some thoughts here.

**Comment by thatbettina** [comment]
@plexus I thought it was Friday night at your house?! Or maybe @vsmart can't make it on Friday?

**Comment by plexus** [comment]
That's something else, you should have an invite in your mailbox.

My notes:
- Better divide the work

This workshop was a bit of a special case because we started quite late organizing, and then also had the holidays in between. I knew I was going to be without a job in January, so I could do whatever I saw needed doing, but I can't do that a second time.

We can remedy that somewhat by starting earlier so the work can be better spread over time. I also hope to see people more proactively looking for things that need doing, and less backseat driving.

I have a few people in mind that I think would be good candidates to join core, but this is something we should talk about in person. More people also means more people management. 
- Work more closely with ClojureBridge

This is one of the things I wanted to focus on more already this edition, but that fell on the wayside because everything else had higher priority. I believe only very few of the organizers are on the ClojureBridge-workshops mailing list, that's not good, we're being too much an island. 

We've done extensive editing on the curriculum, and some of us are interested to do a lot more work on it in the future, we need to start a dialogue with the board and with other chapters about where we want to head with that.

Some of the things we do are quite unique, or are inspired by people's experience with Rails Girls. For example our way of doing sign-ups and RSVPs. We have an exceptionally low no-show ratio because of this, more people should know about that.

We have been gradually creating our own organizing materials, while there is also a lot of stuff in the (global) Clojurebridge/organization repo. That repo needs cleaning up and improving, there's a lot we could contribute there.
- lifecycle emails

Right now people signed up and didn't get any feedback that they were even on the list until a few weeks before the workshop. We should at a minimum automate an email to confirm they are signed up, and to let them know about the selection process and that they will hear back from us at time $x. The same goes for the coaches. Three to four weeks before the workshop we could send another email with a small update on how the organization is going.
- Work out sponsor tiers

This time we had a lot of small sponsors, but each sponsor creates extra works. It usually takes four to six emails back and forth before we have the info of their payment, then it's a couple emails back and forth with Travis to get the receipt. We need to get their logos on our site, on the ClojureBridge site, on swag, etc. I think we've learned a lot about how to approach companies by now, and we can have a much clearer message prepared.

Not doing this over the holidays and starting earlier should already take a lot of the stress out of this. Getting companies to pay takes patience, if we have a longer time frame it's easier to just sit back and let them do it at their own pace.
- prepare follow-up emails beforehand

Everyone wants a break after workshop day, but there's also some follow-up that needs to happen and it's better to not wait too long with that. We should plan beforehand what emails we want to send when, and have an initial version ready where we can just fill in the blanks.
- kitchen management

I would really like to find some volunteers for this next time. One or two people, maybe previous attendees, who throughout the event take care of the kitchen. Filling up dishwashers, putting out and putting away food, receiving the caterer. With breakfast, lunch, and afternoon snacks this is basically a full-time job. The kitchen is also the first place people go whenever they have a break, so there are people coming and going all day. Having that space looked after makes things more pleasant for everybody and means we can leave in time in the evening.
- InstallFest reception

We should do a better job of managing expectations at the InstallFest. It might be a good idea to start with a short intro talk to welcome everybody and explain what's gooing to happen.

**Comment by Malwine** [comment]
@plexus Thanks for the detailed report.

From my side I want to mention that I really liked the idea with the **instagram account** and that **many people tweeted** about the event.
This time I attended **remotely** (by stalking the web) so it was super cool to get an impression of the event. Big **PLUS** for that. Visibility of our work is good and important! Especially for people not attending e.g. sponsors, people who potentially want to start a similar event etc.

**Comment by thatbettina** [comment]
My thoughts regarding organizing the speakers:
- I liked that I communicated with all them, getting confirmation that they still want to talk, what exactly they wanted to talk about, etc.
- I wish that I had remembered to do a tech check during the install fest with the speakers.

**Comment by plexus** [comment]
Notes from the retrospective:

## Visibility / Social Media

Liked the instagram account, makes it easy to experience it when you're not
attending. Past/future attendees, sponsors, interested others.

Even more would be great, might be good to have a person dedicated to that.

Scheduling tweets/mails is very handy

## Keep it bilingual

This is a big asset, there are always people who are not comfortable with only
English. Curriculum in English is not a huge issue if the coach can translate.

## Better outreach

Think more active about our target group, find other avenues to reach out. Now
it's mostly inside tech commonities, which is already great, e.g. people coming
from Ruby. Other ideas: radio, blogs, magazines, universities.

## Lightning talks

Nice and diverse. Gave a good portrait about what it means to be a programmer.

Having them at the end was a bit tiring, might be better to have them earlier.

Demo time was a bit too pushy? Would be cool if people can share their quil sketches and let us demo/show them.

Project group talk at the end was good to close things off. 

It would be good to have at least one in German.

## Post-workshop

Good call to action, good sales pitch for the project group.

## Sponsors

Not a clear story, we don't have a clear message of what to say or what to ask
for. There are no pricing tiers, it's not clear what perks you can or can't get.
We need to set clear expectations.

Letting companies do pitches: not cool, but maybe having a booth is ok?

## Curriculum

Some groups were very late to start with Quil.

Very hard to have something that fits for all levels.

Could be something for a working group to work on.

## Coaches

Some people didn't like being floating coaches, others did a great job at
floating, or actually prefer it, so it's something we should ask on the signup.

Some coaches weren't on the list.

Coaches training: maybe second timers can skip?

Trim the deck: it takes too long.

In the form: photographs or not?

## InstallFest

The reception needs to be better, setting clear expectations, pointing people in
the right direction.

Have a starting time when we do a small intro talk. Maybe do most of the intro
talk from Saturday already on Friday.

Should we have all the coaches there or only the mimimum? Some people were
uncomfortable with so many men there.

There were often groups of male coaches sticking together, that's not so good.

## Attendee management

Attendee form was very good and complete.

Would be good to check if people want to be together.

Notebooks were very good, directly used. Spontaneous swag table was cool. Real
bummer that we didn't have new stickers.

**Comment by Malwine** [comment]
Thanks @plexus :100:

**Comment by vsmart** [comment]
Thank you for going through these and the retro & thanks @plexus for posting :+1: 
I think they cover all that I wanted to add too.

**Comment by Malwine** [comment]
@vsmart said this in a PR comment:
`Actually this was something I wanted to give feedback on and forgot. I think it's kind of nice for attendees to be able to customise their own name tag. I see the advantage of having someone prepared for everyone - especially with the photo preference sticker - but I think letting people pick what name they want their name tag to have is better. it's just a small thing but it's easy for us to do. In fact it is possibly less work for us this way! What do you think?`

**Comment by thatbettina** [comment]
:+1: for the DIY nametags

**Comment by plexus** [comment]
DIY nametags it is!
