### ISSUE TITLE
Post-workshop coaches email

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#66]
Let's send one to the coaches too.

1) Asking for feedback. (Is there a form or is this casual version ok?)

2) Thanking them for coaching. 

3) (Maybe) Inviting to the project group? Not sure about this one. We want to avoid another situation where it's mostly coaches and only 1 or 2 learners like last time. 

4) Do we need a German version too? I guess it's assumed that all coaches speak English. 

---

Draft (English)

Hi coaches, 

We'd like to check in on you now that the ClojureBridge workshop is well past. 
### Thank you <3

Firstly, a big thank you for coaching. Without your participation, hard work and dedication we could not run these workshops. We hope you enjoyed it too and maybe learned some things as well. 
### How did coaching go for you?

It would be great to hear some feedback from you about the workshop. 
Do you have any feedback regarding the coaches training? 
How about the install fest? 
How did you feel about the workshop itself? Is there anything you feel we can improve with regards to supporting the coaches?
### Did you speak at ClojureBridge?

If you spoke at ClojureBridge, what did you like? How can we improve the organization beforehand as well as during the workshop itself?
If you applied to speak at ClojureBridge but didn't speak, we're interested in your feedback too!

Please email us back with your feedback. 

If you have any comments with regards to the curriculum, you are welcome to create issues and submit pull requests here: https://github.com/clojurebridge-berlin/curriculum. 

Cheers

**Comment by thatbettina** [comment]
+1 for the idea

Would it be possible to add to this email something like:
"If you spoke at ClojureBridge, what did you like? How can we improve the organization beforehand as well as during the workshop itself?
If you applied to speak at ClojureBridge but didn't speak, we're interested in your feedback too!" 

Since all the speakers were also coaches, I think it would save everyone one extra email if we include these two lines. Plus, they have one experience: as a coach or as a coach and a speaker, so it's good to just include the feedback on the same email.

Let me know what you think :)

**Comment by thatbettina** [comment]
Here are my thoughts to your questions:
1. Yes, free field answers are the best.
2. Yes!
3. Someone who's managing the project groups--how is it on Wed? Is there a need for another day of the week?
4. I don't know enough coaches to be able to comment, but it could be our general policy to be bilingual. I'm ok personally either way but some orgas have stronger opinions on this than me.

**Comment by vsmart** [comment]
Thanks @thatbettina, I added your line about speakers contact to the email draft above.

**Comment by vsmart** [comment]
Sent!
