### ISSUE TITLE
Core Team Meeting III — agenda

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#85]
I'm gathering thoughts here, feel free to edit and/or comment.

Follow up from last meeting
- Phrasing of target audience<br>
  Wrap up https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/pull/22 so we can get that onto the site.
- Food<br>
  For coaches training/installfest/lunch things are moving, Cate Lawrence will be our caterer again.<br>
  Any news on cupcakes/breakfast? (Nicola)
- Afterparty<br>
  Conclusion last time: Prater Garten if the weather is nice, backup options are Kaschk or Volksbar. Do we stick with that or are there other ideas? <br>
  Who will make the reservation for the backup place?

New stuff to be discussed
- Attendees<br>
  Status update + get ready to invite the first batch
- Coaches<br>
  25 coaches signed up. Do we invite them all? <br>
  We need to start prepping the coaches training <br>
  - invite/remind the coaches. Email needs some work but is largely reusable. ([email template](https://github.com/clojurebridge-berlin/organization/wiki/[email]-Coaches-Training-Reminder))
  - pick a host/MC
  - edit and study slide deck (-> needs to be more compact/condensed, host should know the material)
- Email schedule<br>
  We'll be sending out a bunch of emails before and after the workshop. We can really make our lives easier by preparing those up-front. <br>
  Task: make a schedule of what to send to whom at what time, and write/update the corresponding email templates
## Action items

to be assigned
- prepare coaches training — Arne/Franziska
  - pick coaches and invite them  
  - host/mc
  - edit and send out reminder emails ([template](https://github.com/clojurebridge-berlin/organization/wiki/[email]-Coaches-Training-Reminder))
  - email Brandon about accessible toilets 
- order cupcakes — Nicola
- order breakfast — Nicola
- <del>make reservation for afterparty</del>
- plan/schedule/write lifecycle emails — Arne will start on this and try to divide the work
- resolve/merge the "phrasing" PR https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/pull/22 — Malwine
- Order language stickers on nametags (so people can add them on the day)
- Sort out lanyards for orga team

**Comment by Malwine** [comment]
Point of discussion:
- What do we do with the old data that we have? We should not keep personal data of people.

**Comment by socksy** [comment]
## Minutes
- Contact the volunteers, probably for the day
  - Brandon is a coach
  - Tamara and Silvia haven't signed up, we should message them directly
- Phrasing of target audience
  - Action item to finish https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/pull/22
- Food
  - Main Food for the event
    - Arne contacted caterer from last time, with vague terms
    - Cognitect troubles with not supporting paypal, but are now supporting wire transfers
    - Cate given carte blanche with 900€
  - Cupcakes and breakfast
  - **Nicola** said she'd do all this
- Afterparty
  - Prater, no reservation, no more to be done
- Attendees
  - Status
    - First batch sent out already
    - Already got a couple confirmations and rejections
    - Deadline for this batch is Friday
  - **Julia and Ben** doing second batch after Friday (and every other batch after)
- Coaches
  - Choosing them
    - Want to contact the women first
  - Thinking about not inviting all, ~15 in total at first (better to have a 2:1 ratio than a 1:1 ratio)
  - Franks makes the point that if someone is invited to coach training it's not a good thing to then decline them
  - Malwine suggests having two mails, one for definitely coaching, one for "we would like to have you around"
  - Contact 20 people (assuming around 3/4 floating), assume a few will drop out
  - Already greenlighting some people on the coaches list
  - Redrafting (condensing and adding study material) **Arne and Franziska**
- Email Schedule
  - Make a timeline for which mails to send when (as a Trello ticket?) **Arne**
  - In the timeline have link to email template for each point
  - Different people set to different sets of emails
- Retrospective schedule
  - Ben has been noting when we did various things, in order to check 
- Data privacy (Germany and Google Forms is dubious)
  - It'd be nice to know who has been rejected/accepted before when making the decision, and maybe delete the rest of the data
  - However, we haven't done it, so this is academic, and it's also probably against the law just to have emails on record
  - _TODO_ So we shall delete everything and just ask people when selecting next time
  - _TODO_ We also forgot to ask people whether they want to be on the mailing list on the sign-up form, so we need to ask in the feedback form on the day whether they want to be on the mailing list
- Childcare
  - Next time "Help with childcare" in the form?
    - Then we can have a talk with them, and see
  - This work shop, we'll ask with final information email
    - _TODO_ But perhaps we should ask around for baby sitters now to see, because it might not be possible last minute **(Julia and Franks already starting on this)**
- Nametags
  - Language stickers on nametags
  - Lanyards for orga team
