### ISSUE TITLE
ClojureBridge Orga hoodies

### ISSUE THREAD

**Issue by nicsnet** [clojurebridge-berlin/organization#96]
At the last core orga meeting held on September 15th, we briefly touched upon the topic of t-shirts, hoodies and merch. Since we have enough ClojureBridge notebooks to last us many a workshop, we might want something additional to provide attendees with as a token of fond remembrance and subtle marketing for us. If it's not feasible in the short timeframe that remains, there is still the option to get the organisers something. It could be beneficial to organisers to be able to represent themselves visually other than a name tag. So what do you all think of orga hoodies? I'm really a fan of the [github hoodies](http://github.myshopify.com/products/invertocat-hoodie). We could even copy their style, e.g. have the CB logo on the front and on the back at the bottom either "orga" or "orga team" or whatever fits.

What do you think?

**Comment by plexus** [comment]
I would <3 a ClojureBridge hoodie, I also like the idea of making generic "ClojureBridge Berlin" t-shirts so we sidestep some of the logistical difficulties, as suggested on the last meaning.

My main argument against it is "keep it simple", we already have a lot of things to do and think off, and this one is really not a necessity.

I guess in the end it just depends if someone wants to run with it. Propose a design, ask for quotes from one or more printers, consider delivery time, etc.

If we go for it it would be good to know early and set an estimated budget for it, so we can take that into account when fund raising.

**Comment by martinklepsch** [comment]
Unless there's someone else who wants to run with this I'm open to take on this one. I really like having some clothing and even though I'll not be there I'd be excited about everyone going home with something that the can represent with later :)

**Comment by codebeige** [comment]
I would love to contribute to the design and can also check out pricing, options and specs from suppliers. Where did we order the T-Shirts last time? @martinklepsch Do you warnt to collaborate on that?

**Comment by plexus** [comment]
Last time we ordered from cotton.de, the t-shirt model was "Stanley and Stella". This and much more details about what we did last time can be found here: https://github.com/clojurebridge-berlin/organization/blob/master/2015-07-11-factbook.md#tshirts

note to self: I should really work on a factbook from the previous workshops, I guess these things come in handy sometimes :)

**Comment by codebeige** [comment]
Thank you for the link.  I will check it out and I also keep in touch with with @martinklepsch

**Comment by nicsnet** [comment]
I checked [cotton.de](http://www.cotton.de/) they also have hoodies [stanley tours](http://www.cotton.de/fair-bio/stanley-and-stella/stanley-tours/) and [stanley travels](http://www.cotton.de/fair-bio/stanley-and-stella/stella-travels/)

**Comment by codebeige** [comment]
Did some research among (environmentally sustainable) textile printers online and the offer at  [cotton.de](http://www.cotton.de/) seems pretty reasonable to me. I also do like the hoodies from [Stanley and Stella](http://www.cotton.de/fair-bio/stanley-and-stella/). So we should probably go with it.

I will come up with a design, and then we have to decide about the number of pieces we would like to order. Delivery should then be possible within two weeks or even less.

**Comment by codebeige** [comment]
![160927 clojurebridge berlin](https://cloud.githubusercontent.com/assets/91858/18876712/051662e0-84cb-11e6-8f28-700c9a2a8051.png)
Here is my take on the ClojureBridge Berlin chapter logo so far. It could simply be placed in the front left like with the GitHub hoodies, but I can also imagine having a huge print on the back.
I chose "India Ink Grey" for the color. Unfortunately that one is only available for [stanley tours](http://www.cotton.de/fair-bio/stanley-and-stella/stanley-tours/).

**Comment by Malwine** [comment]
Btw, we discussed **not to support** Stella and Stanley as a brand **anymore** because their branding and product names are **anti-feminist** which stands in the way of our mission.

Please consider other brands such as [EarthPositive](http://www.cotton.de/hersteller/earthpositive/) or [Continental Clothing](http://www.cotton.de/hersteller/continental-clothing/).
Thank you.

**Comment by codebeige** [comment]
@Malwine Please excuse my ignorance, but why exactly is it anti-feminist? Is there any record of this discussion that you had earlier?

Also I feel tempted to close this issue entierly, as from the conversation on slack it seems we are not all on the same page here. Maybe a short vote during our next meeting can help clarify things.

**Comment by socksy** [comment]
@codebeige seems that there was no record at the time, most likely due to
teething process of the first workshop. The sexist marketing is with the
verbs being used to identify each shirt, with the men's shirts:

Stanley "Leads" but Stella "Wants". 
Stanley "Performs", but Stella "Plays".
Stanley "Acts", but Stella "Desires". 
Stanley "Knows", but Stella "Says".
Stanley "Runs", but Stella "Cuddles". 
And so on.

**Comment by codebeige** [comment]
@socksy Thank you for clearing up. Now I can see the problem.

If we want to go on with it, I would probably decide for the [EarthPositive Hoody](http://www.cotton.de/hersteller/earthpositive/ep60z-hooded-jacket/). Navy blue with white cord and white printing could work out pretty well.

A cheaper alternative would be the [Continental Clothing Unisex Hooded Zip Sweatshirt](http://www.cotton.de/hersteller/continental-clothing/unisex-hooded-jacket/).

Both models are unisex, which might also be beneficial when producing a batch in advance.

**Comment by codebeige** [comment]
![161014 orga hoodie](https://cloud.githubusercontent.com/assets/91858/19387861/1db0db46-921d-11e6-870c-defbd34cffc5.png)

I would do a classic positioning of the logo just like the Github hoodies. Maybe we also want to have the Twitter handle on the back as with the #117 . Would be hidden by the hood most of the time. A "hidden feature" or "easter egg" so to say.

**Comment by Malwine** [comment]
@codebeige I like the hoodie a lot :) I would really like to have one.

There's a little thing I want to draw your attention to: 
It would be cool to have the logo close to the zipper and a bit up. Why?

Because there is a problem we already had for the t-shirts last year: 
**for women the logo slips to the side between armpit and breasts and just look strange.**
Proposal:
![screen shot 2016-10-14 at 17 52 13](https://cloud.githubusercontent.com/assets/5123681/19394038/9d84d29a-9237-11e6-995b-b77e6cc81fc3.png)
I can recommed trying out the designs on woman pictures too. This way you get an idea how the fabric folds in the front.
E.g.
![screen shot 2016-10-14 at 17 58 35](https://cloud.githubusercontent.com/assets/5123681/19394136/124581ce-9238-11e6-82b1-45d936ff6f6c.png)
![screen shot 2016-10-14 at 17 59 20](https://cloud.githubusercontent.com/assets/5123681/19394142/15e63990-9238-11e6-9823-384991c02592.png)

Here is another example where the logo should probably be:
![screen shot 2016-10-14 at 18 04 56](https://cloud.githubusercontent.com/assets/5123681/19394308/de69550a-9238-11e6-84d0-6a3bc21c1007.png)

Thanks for considering this!
❤️

**Comment by codebeige** [comment]
I totally agree with that.

It was just meant to illustrate the overall idea, and then the cord of the hood was in my way. But what is a mockup worth, if it is not correct… Thank you for the clarification.

**Comment by codebeige** [comment]
The design will be the same as #117 , but on black background. Closing this as we will probably order them together with the t-shirts anyway.

**Comment by codebeige** [comment]
Reopening this for taking orders from the orga team (and friends). I will reach out to [cotton.de](http://coton.de) for the exact pricing. Should be about € 30 per piece.

**Comment by codebeige** [comment]
We need to have at least 10 orders for us to allow proper screen printing. Also printing will be much more expensive for a very small batch. Please leave a comment here with your size, if you are willing to pay up to 50 € for it.

**Comment by lislis** [comment]
I would get one, size L

**Comment by nicsnet** [comment]
I'm in, can I have a fitted M?

**Comment by socksy** [comment]
Oh go on then, straight cut M.

**Comment by Realtin** [comment]
I get one in straight cut XL

**Comment by codebeige** [comment]
The [EarthPositive Hoody](http://www.cotton.de/hersteller/earthpositive/ep60z-hooded-jacket/) only has a single cut. I know this is unfortunate, but the overall quality seemed best.

**Comment by nicsnet** [comment]
That's fine for me then, I'll take M.

**Comment by thatbettina** [comment]
Can I get an M too? Thanks for organizing this @codebeige

**Comment by ioctaptceb** [comment]
straight cut M for me too!

**Comment by vsmart** [comment]
L for me pls! Thank you @codebeige ❤️

**Comment by plexus** [comment]
M for me please. Thanks @codebeige for organizing this!

**Comment by codebeige** [comment]
Counting 9 so far (including XL for myself), so we only need 1 more! 👕 @Malwine Would you maybe interested?

**Comment by nicsnet** [comment]
My boyfriend also wants one, so I'm getting him one 😉 
He'd like the hoody without the zipper also from [Earthpositive](http://www.cotton.de/hersteller/earthpositive/ep60p-hooded-sweat/) in black in size L

**Comment by codebeige** [comment]
🔔 So we have reached the minimum amount for an order! 🎉

Any additional takers are very welcome. So I will wait until the day after tomorrow before I finally place the order.

**Comment by saskali** [comment]
I would take an M hoody without zipper, thank you!

**Comment by ariaru** [comment]
I would like an M please. Thanks for organizing this, and for letting me join the hoodie order without being an organizer myself :)

**Comment by codebeige** [comment]
Cool, thank you for your orders. I will now contact cotton.de and get a quote for these.

**Comment by codebeige** [comment]
Turns out the Hoodie with Zipper in XL is currently out of stock and not available until 2017. Without Zipper in M and L is also only available from end of November.

If we want to get them for the upcoming workshop, the only option would be the [Hoodie with Zipper from Continental Clothing](http://www.cotton.de/hersteller/continental-clothing/unisex-hooded-jacket/) (without zipper also currently unavailable).

I am not really convinced. But what do you think? Lets take a vote. Please react on this comment with 👍 if you want to proceed and 👎 for delaying it.

**Comment by codebeige** [comment]
Ok, closing this. 😿

**Comment by Malwine** [comment]
@codebeige Can't we order the hoodies as soon as they have them again? We dont need to have an event running, right? we all were involved with clojurebridge and why should we not have hoodies if we want them?

**Comment by socksy** [comment]
@Malwine that was my understanding of the conclusion of this discussion :)

The issue is closed because of the place on the workshop's project board.

**Comment by Malwine** [comment]
@socksy Oh ok, I was just wondering about the crying cat...
