### ISSUE TITLE
Create the Registration Form

### ISSUE THREAD

**Issue by Realtin** [clojurebridge-berlin/organization#97]
Previous _Registration Form Issue_ for reference:  https://github.com/clojurebridge-berlin/organization/issues/71

**Comment by socksy** [comment]
@sklind started a version here: https://docs.google.com/forms/d/1lNwdYa6zl4LVXk7l5jkgDWYtnM7TxHHMqoE08-Vc26Y/edit (thanks Saskia!)

I was wondering if we can remove the photo permission question, as it's quite daunting, not a legal requirement to get them to understand the copyright of the photos (instead, we would only need their permission to be in the photo of which copyright is owned by us), and I would rather we don't have it in the signup at all. 

Instead, on the day, I propose we do a traffic light system (Red - No photos, Orange - Ask first, Green - Go ahead!), with the copyright statement next to the red/orange/green stickers before they pick them up. This has two benefits: 
1. Less stuff on form, especially complex stuff with the copyright notice 
2. They can change their mind by the day (which they basically could have done anyway before, but we would have written record the wrong way)

**Comment by socksy** [comment]
Also, I have a question for either @martinklepsch or @plexus: How did you set up the confirmation email? I would propose keeping it the same as before, filled in as follows:

> Hi [Person],
> 
> Congratulations, you are now registered for ClojureBridge Berlin! The workshop takes place on a Friday evening and Saturday during the day, 25th and 26th November. Make sure to mark the date in your calendar!
> 
> Unfortunately places are limited so we can't yet guarantee you a spot. We will get back to you once registration closes (6th November).
> 
> Best, ClojureBridge Berlin Team
> 
> Hi [Person],
> 
> du hast dich erfolgreich für ClojureBridge Berlin registriert. Der Workshop findet am Freitag, den 25. November und Samstag, den 26. November statt. Wir bitten dich, diese Daten zu notieren.
> 
> Leider gibt es immer mehr Bewerbungen als wir Plätze anbieten können, deswegen melden wir uns nochmal nach dem Ende der Anmeldefrist (am 6. November) und teilen dir mit, ob du ausgewählt wurdest.
> 
> Bis dann, ClojureBridge Berlin Team

**Comment by plexus** [comment]
Was that form created using "Make a copy" on the previous form? Just asking because I want to properly document this stuff, we've had issues in the past when trying to re-use the old form.

It seems this one was still linked to the old spreadsheet, if you went to "results" and click the google sheets icon you would get all the attendees from the previous workshop.

I "unlinked" the sheet from the form (not sure you could do that in the past, but it works now), then when you click on the sheets icon under "results" it asks if you want to make a new spreadsheet, which I did, so now we have a clean slate.

Ben, this is the template we used before. Did you change anything besides the date?

https://github.com/clojurebridge-berlin/organization/wiki/%5Bemail%5D-Attendee-Signup-Confirmation-Email

Setting up the emails is done through a forms add-on. In the form, in the top-right menu choose "Add-ons". There's one called "Form Notifications"

**Comment by plexus** [comment]
Checklist for future reference: https://github.com/clojurebridge-berlin/organization/wiki/Creating-a-New-Sign-up-Form

**Comment by Malwine** [comment]
I was wondering if we should have a question if the person is a person of color. yes/no answer. Women of color in tech are hit by a double discrimination many times so in this way we could explicitly help to support.

**Comment by socksy** [comment]
@plexus No change other than the date (using your template changer app). Am I right in understanding that all is left with this sign-up is to use this plugin?

I think adding a PoC question is a good idea, but maybe worth discussing further exactly... Until now, nothing in the questions would affect the chance of getting into the workshop. Should there also be e.g. a free text box to let people of various disadvantaged backgrounds add something should they think its pertinent? Or maybe this would make things too complicated.

And anyone have thoughts on deleting the photo question? I would like to go ahead and do this.

**Comment by saskali** [comment]
@plexus Yes, the form was created using "Make a copy" on the previous form. I just finished setting up the confirmation emails with the Add-on now.

@socksy From my own experience, I remember that people at the workshop didn't remember which option they chose on the photo permission question. So I think, it's a good idea to remove the question from the sign up and instead ask them directly on the day of the workshop.

**Comment by vsmart** [comment]
**+1 for adding are-you-a-PoC question** 
   (I like the formatting Malwine suggested: simple yes/no answer).  
**+1 for removing photo question**
(... and use our sticker traffic light system only - especially since we never cross-referenced our photos with the initial questionaire again in the past. Removing clutter on the sign up form is almost always a plus in my head. OTOH it might be valuable to have this privacy preference documented somewhere per person - @lislis @jellea I'd be curious to hear your input on this one.)

**Comment by lislis** [comment]
+1 for a PoC question. But I would add an explanation to what we mean by that. It might not be apparent to all who want to apply and uncertainty might make them drop the application alltogether

+1 for removing the photo question from the signup form. But I'd like to maybe have a little paragraph in one of the emails leading to the workshop (or a link to a page explaining this) that we might take photos and that there will be opt-out possibilities. So that attendees have heard/ read this once before coming to the workshop so they kind of know what's going on and are not too surprised.

**Comment by Realtin** [comment]
I'm worried that the PoC Question is kinda creepy

**Comment by vsmart** [comment]
What do you think about:  

Are you a person of color? // Bist du eine Person of Color? 
 _It's important to us to include attendees from a variety of backgrounds. We select our attendees randomly, but if there are free spots we love to give preference to PoC who are often underrepresented in tech communities._  
 **=> Yes - No - Prefer Not to say**

Also, I removed the photo question.

**Comment by vsmart** [comment]
Can I remove the tshirt question?

**Comment by Realtin** [comment]
Ok I asked a friend who is a PoC and she had a great idea! 
She said that an open question like **'how would you identify yourself?'** would be better because a person of color that politically identifies herself as such would write that. And you will also get a wider range like 'women of color, trans of color, qtpoc....' 

what you all think? I feel more comfortable asking it that way.

**Comment by lislis** [comment]
@Realtin would this be a text-field then? Might make it trickier to evaluate the responses later, but it's definitely a great approach 👍

**Comment by socksy** [comment]
@Realtin I like this, but there's already a plain text field for gender. It feels weird to ask twice, since most people identify as a gender. 

But if we put "What do you identify as?" instead of gender, then some people will be confused. 

Especially white men, who we're using the gender field to double check they haven't applied to the wrong event (something that has happened multiple times in the last few workshops), will be unlikely to fill this in correctly.

**Comment by Realtin** [comment]
ah yes I would be for a combined question. 
where it just says _What do you identify as?_
(maybe with an example under it or a litte explainaition)
But I see what you mean which checking for the gender especially. ...  maybe something like

**What do you identify as?**
_This Workshop is targeted towards women*, please make sure that you at least specify your gender identification [but feel free to include whatever else you feel comfortable with disclosing]_

?? I don't know .. or 2 fields (one for gender and one for everything else)

**Comment by vsmart** [comment]
====> https://goo.gl/forms/N0HDG6tOzE4niKYC2 🎉

**Comment by vsmart** [comment]
for reference, we decided to: 
- remove the photo question
- not include a are-you-a-PoC question (focus on outreach to underrepresented groups instead)
