### ISSUE TITLE
Sponsors November 2016

### ISSUE THREAD

**Issue by nicsnet** [clojurebridge-berlin/organization#98]
I copied this over from the last sponsering issue

Potential sponsor. Box ticked == has been contacted --> put your name after the company name in parens.
~~strike through~~ == out
**bold** == accepted
- [x] ~~8th light (franka)~~ 
- [x] ableton (franka/tamara)
- [ ] Adjust 
- [ ] Asquera
- [x] **Babbel** (Nicola)
- [x] **bitcrowd** (Yulia)
- [x] Blacklane (franka)
- [ ] codecentric
- [ ] Cognitect (Arne) 
- [x] Contenful
- [ ] Dawanda
- [x] Futurice (julia)
- [ ] Fy (Jelle)
- [x] Github (Nicola)
- [ ] Hitfox
- [ ] ImmoScout
- [x] **InnoQ**
- [ ] Jayway
- [ ] Juxt 
- [x] ~~Lambdawerk [franka]~~
- [x] ~~Metosin [franka]~~
- [ ] Mixcloud
- [ ] MixRadio
- [ ] N26
- [ ] O'Reilly
- [ ] Otto
- [ ] Red Pineapple Media (Ben)
- [ ] Pragmatic Programmers
- [ ] PurelyFunctional.tv
- [ ] Siili
- [x] Small Improvements
- [x] **SoundCloud** (Yulia)
- [x] ~~Tape.tv~~ (Nicola) 
- [x] **Thoughtworks** (Nicola)
- [ ] Ticketsolve
- [ ] Twilio
- [x] **Wunderlist/Microsoft (Franka) [venue + drinks]**
- [ ] Zalando
- [ ] Studio NAND

**Comment by plexus** [comment]
Thanks @nicsnet, I'd like to suggest that we maybe make an effort to contact some companies that we didn't contact in the past (not all of the above got contacted, and there are lots of other potential sponsors not on the list).

**Comment by socksy** [comment]
This is a big list that seems hard to approach right now. Are there any there that people want to deal with personally, i.e. no canned emails? 

We can probably assume that Babbel, Red Pineapple Media, Wunderlist and Fy are going to be approached like this. What about these others with the parens? I guess it's something left over from last year.

After we filter those out, let's filter those that haven't been contacted before, and assign them in to smaller groups that can be delegated out.

I would also suggest going through the list of [companies using clojure](http://clojure.org/community/companies), and seeing if there's any there that are in Berlin/Germany/nearby that we haven't considered yet. E.G. I immediately spot Pivotal Labs, which have a Berlin office. Also, maybe worth asking Small Improvements, a Java-based outfit in Mitte, since they out of the blue went to sponsor ClojureBridge core (probably they don't know it's a kinda separate entity).

**Comment by plexus** [comment]
I'm going after Contentful, InnoQ, PragProg. Trying to get hold of some German companies that use Clojure: Studio NAND, Doctronic, Bevuta IT.

Talked to someone from Adobe at the Clojure meetup, they're interested, but would ideally be able to pay by credit card. We've had this question in the past, and it's not easy to find suppliers in DE that can do that, but I'm working with Tibor to see if we can arrange something for the t-shirts.

I asked Travis to give us an update of our financial situation.

**Comment by plexus** [comment]
Confirmed so far

| sponsor | amount |
| --- | --- |
| InnoQ | 500 |
| Doctronic | 600 |
| Bitcrowd | 250 |
| PragProg | 5 e-books |
| Soundcloud | 500 |
| Lambda Island | 1 year membership |
| Babbel | 250 |
| Microsoft | venue + drinks |
| Blacklane | 250 |
| ThoughtWorks | 700 |

**Comment by vsmart** [comment]
@plexus added MSFT for venue + drinks to your table

**Comment by plexus** [comment]
Thanks @vsmart, I should have thought of that...

**Comment by vsmart** [comment]
8th light is out for this time. They would like to be present (by sending in a coach) if they sponsor, but it's too short notice this time. We should try to invite them next time :) (My contact there is Jarkyn (twitter.com/indykidd)

**Comment by socksy** [comment]
Contacted Small Improvements, who I was interviewing with 2 years ago, and of which earlier this year donated $1000 to main ClojureBridge organization (from an initiative where employees [got to choose how to spend some donation money](https://blog.small-improvements.com/2016/01/13/lets-do-some-good-an-experiment-in-giving-back/)).

**Comment by nicsnet** [comment]
Babbel is going with the small supporter package (250€) this time around. They will issue a donation for the amount to the travis foundation. I might talk to some higher up management and see if we can get a bit more, stay tuned ...

**Comment by Malwine** [comment]
It would be great to update the website. So the logos of the confirmed sponsors appear before the next workshop.

**Comment by vsmart** [comment]
added blacklane as confirmed sponsor 🎉

**Comment by vsmart** [comment]
@Malwine good point. will create an issue.

**Comment by plexus** [comment]
I'm doing some following up on the sponsors
- Studio NAND will be linked up with Cupcake Berlin. We should order the cupcakes ASAP so we can make sure Studio NAND pays them before the workshop. I remember from the Emacs Berlin anniversary that they can really insist on being paid beforehand. (ping @nicsnet)
- I asked InnoQ if they will pick up the tab for Suppen-Cult. They offered to sponsor 500, and Suppen-Cult is 510 so that should be fine. Once I have the ok I'll try to have them work out the details among themselves. 
- I asked Doctronic to pay to Travis foundation.
- We asked Bitcrowd quite some time back to donate to Travis foundation, I don't think they've gotten a receipt yet. @lithop could you ask them when the payment was made, and what name/address should be on the invoice?
- Blacklane / Soundcloud / Thoughtworks / Babbel should all donate to Travis. Could the people who arranged these sponsorships please follow up on them? I can send you an example email. The important bits are
  - please pay to Travis Foundation (include account info)
  - please add "ClojureBridge" in the purpose/description
  - Travis Foundation is an official non-profit. They will give you a receipt _after_ payment is received, which is an official document that can be booked like an invoice
  - Please tell us when the payment was made so we can easily find it, and which name/address needs to be on the invoice.

Thanks a lot team 🙌 another great fund-raising round :D

**Comment by plexus** [comment]
Update: forwarded the info for the receipts to Travis Foundation for Bitcrowd, Doctronic, Blacklane, Babbel.

Still waiting for confirmation+date of payment + address from Soundcloud and Thoughtworks.

**Comment by plexus** [comment]
Bitcrowd, Babbel, Doctronic have gotten their receipts, and for Soundcloud and Thoughtworks the info has been forwarded to Travis so they can also get a receipt.

The paper receipt for Blacklane will be done a bit later due to someone being on holiday.

**Comment by vsmart** [comment]
blacklane also has not even paid yet, they said they will pay on friday
